name: geolocator
description: Geolocation plugin for Flutter. This plugin provides a cross-platform (iOS, Android) API for generic location (GPS etc.) functions.
repository: https://github.com/baseflow/flutter-geolocator/tree/main/geolocator
issue_tracker: https://github.com/baseflow/flutter-geolocator/issues?q=is%3Aissue+is%3Aopen
version: 14.0.2

environment:
  sdk: ^3.5.0
  flutter: ">=2.8.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: geolocator_android
      ios:
        default_package: geolocator_apple
      macos:
        default_package: geolocator_apple
      web:
        default_package: geolocator_web
      windows:
        default_package: geolocator_windows
      linux:
        default_package: geolocator_linux

dependencies:
  flutter:
    sdk: flutter

  geolocator_platform_interface: ^4.2.6
  geolocator_android: ^5.0.2
  geolocator_apple: ^2.3.13
  geolocator_web: ^4.1.3
  geolocator_windows: ^0.2.5
  # geolocator_linux: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.0.0-nullsafety.7
  plugin_platform_interface: ^2.1.8
